#!/bin/bash
set -euo pipefail
IFS=$' \n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

#########################################################
# setup wacom Wacom Intuos S for drawing with Xournal++ #
#########################################################

STYLUS=$(xsetwacom --list devices | grep "Wacom Intuos S Pen stylus" | grep -oP "\\d+")
PAD=$(xsetwacom --list devices | grep "Wacom Intuos S Pad pad" | grep -oP "\\d+")

# set draw area for 1920:1080 screen
xsetwacom --set $STYLUS Area 0 0 15200 8550

# press -> left click
xsetwacom --set $STYLUS Button 1 1
# lower stylus button -> undo
xsetwacom --set $STYLUS Button 2 "key ctrl z"
# upper stylus button -> pan
xsetwacom --set $STYLUS Button 3 "pan"

# 1st -> select and transform objects
xsetwacom --set $PAD Button 1 "key s"
# 2nd -> edit paths by nodes
xsetwacom --set $PAD Button 2 "key n"
# 3rd -> zoom in
xsetwacom --set $PAD Button 3 "key +"
# 4th -> zoom out
xsetwacom --set $PAD Button 8 "key -"

