#!/bin/bash
set -euo pipefail
IFS=$' \n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

#########################################################
# setup wacom Wacom Intuos S for drawing with Xournal++ #
#########################################################

STYLUS=$(xsetwacom --list devices | grep "Wacom Intuos S Pen stylus" | grep -oP "\\d+")
PAD=$(xsetwacom --list devices | grep "Wacom Intuos S Pad pad" | grep -oP "\\d+")

# set draw area for 1920:1080 screen
xsetwacom --set $STYLUS Area 0 0 15200 8550

# press -> left click
xsetwacom --set $STYLUS Button 1 1
# lower stylus button -> undo
xsetwacom --set $STYLUS Button 2 "key ctrl z"
# upper stylus button -> middle click -> pan (you might have to tell Xournal++ that the stylus is a "mouse", not a "pen")
xsetwacom --set $STYLUS Button 3 2

# 1st -> use pen
xsetwacom --set $PAD Button 1 "key shift ctrl p"
# 2nd -> use eraser
xsetwacom --set $PAD Button 2 "key shift ctrl e"
# 3rd -> select region
xsetwacom --set $PAD Button 3 "key shift ctrl g"
# 4th -> add new page
xsetwacom --set $PAD Button 8 "key ctrl d"

